project:
  type: book
  output-dir: docs

book:
  title: "R Guide"
  author: "Jaewon Kim"
  date: "2025. 12. 13."
  chapters:
    - Introduction.qmd
    - Structure of R Studio.qmd
    - Introduction to Data.qmd
    - Vectors.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

