project:
  type: book
  output-dir: docs

book:
  title: "R Guide"
  author: "Jaewon Kim"
  date: "2025. 12. 13."
  chapters:
    - index.qmd
    - 1_Structure_of_R_Studio.qmd
    - 2_Variables_Calculations.qmd
    - 3_Vectors.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

