project:
  type: book
  output-dir: docs

book:
  title: "R Guide"
  author: "Jaewon Kim"
  date: "2025. 12. 13."
  chapters:
    - index.qmd
    - Structure_of_R_Studio_1.qmd
    - Variables_Calculations_2.qmd
    - Vectors_3.qmd
    - Matrix_4.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

